### ISSUE TITLE
The plugin is ignored by registrant after Flutter 3.27

### ISSUE THREAD

**Issue by AlexV525** [wang-bin/fvp#192]
See https://github.com/flutter/flutter/issues/160143.

The workaround is adding the dependency to the app project.

**Comment by stuartmorgan** [comment]
As noted in the flutterr/flutter issue, [this registration system](https://github.com/wang-bin/fvp?tab=readme-ov-file#how-to-use) was relying on a bug in Flutter that was fixed in 3.27. Previously Flutter would build and register *all* native implementations of a plugin that were present in the transitive dependency tree. Now it (as originally intended, as documented in the initial design document) will only include the native implementation that fits the [selection criteria](https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit?tab=t.0#heading=h.rky4syx8vrqs).

The right way for an application using `video_player` to select an alternate implementation is to depend directly on that player in its `pubspec.yaml`, rather than to manually call registration code.

Which raises a potentially related question: why does this plugin [depend on `video_player`](https://github.com/wang-bin/fvp/blob/a39b8c399023e826afc206ba0e006640daae7719/pubspec.yaml#L23)? Having an implementation of a plugin depend on the app-facing package of the plugin isn't an intended part of the federated plugin design.

**Comment by wang-bin** [comment]
Because the plugin also provides extension of [VideoPlayerController](https://github.com/wang-bin/fvp/blob/v0.28.0/lib/src/controller.dart).

**Comment by AlexV525** [comment]
That would be no help with the current circumstances. The remaining thing we probably do is add a notice that the dependency must be declared in the app projects.

**Comment by wang-bin** [comment]
> That would be no help with the current circumstances. The remaining thing we probably do is add a notice that the dependency must be declared in the app projects.

so other plugins have the same problem?

**Comment by stuartmorgan** [comment]
> so other plugins have the same problem?

I'm not aware of any other plugins that aggregated a set of possible overrides of another plugin's implementations into a single meta-plugin using a Dart-based registration scheme to select which ones to use on a per-platform basis at runtime. That is what no longer works.

You have several options that I can see:

1. You could keep the current plugin structure, but remove the API that is intended to allow opting in. Clients would either depend directly on `fvp`, in which case they would get the `fvp` implementation on all platforms (and not build the native portions of the `video_player_*` default implementations), or they would get none of them.
2. You could split it apart into one plugin per platform. Clients would depend directly on whichever overrides they wanted.
3. You could split into two plugins:
    - One would be a plugin containing all of the implementations, and would *not* declare itself as implementing `video_player` in `pubspec.yaml`.
    - One would contain the client-facing Dart code, including the registration system, and no native code, and declare itself as a video_player implementation.
    
    This structure should allow you to keep all of the same behaviors as you had before—with the same primary drawback, which is that clients are shipping the native code for two implementations of `video_player` but only using one of them.
